In [2]:
!pip install lenskit

import lenskit.datasets as ds
import pandas as pd

data = ds.MovieLens('data/')

Requirement already satisfied: lenskit in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (0.11.1)
Requirement already satisfied: pandas>=0.24 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (1.0.5)
Requirement already satisfied: numpy>=1.16 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (1.19.5)
Requirement already satisfied: numba<0.52,>=0.45 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (0.50.1)
Requirement already satisfied: pyarrow>=0.15 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (3.0.0)
Requirement already satisfied: scipy>=1.2 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (1.5.0)
Requirement already satisfied: cffi>=1.12.2 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (1.14.0)
Requirement already satisfied: binpickle>=0.3.2 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from lenskit) (0.3.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24->lenskit) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24->lenskit) (2020.1)
Requirement already satisfied: llvmlite<0.34,>=0.33.0.dev0 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from numba<0.52,>=0.45->lenskit) (0.33.0+1.g022ab0f)
Requirement already satisfied: setuptools in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from numba<0.52,>=0.45->lenskit) (49.2.0.post20200714)
Requirement already satisfied: pycparser in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.12.2->lenskit) (2.20)
Requirement already satisfied: msgpack>=1.0 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from binpickle>=0.3.2->lenskit) (1.0.0)
Requirement already satisfied: six>=1.5 in /Users/DDM/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas>=0.24->lenskit) (1.15.0)

In [3]:
!git clone https://github.com/DudJuz/Movie-recommendation-system.git
data.ratings.head(10)

Cloning into 'Movie-recommendation-system'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.

   user  item  rating  timestamp
0     1     1     4.0  964982703
1     1     3     4.0  964981247
2     1     6     4.0  964982224
3     1    47     5.0  964983815
4     1    50     5.0  964982931
5     1    70     3.0  964982400
6     1   101     5.0  964980868
7     1   110     4.0  964982176
8     1   151     5.0  964984041
9     1   157     5.0  964984100

In [4]:
joined_data = data.ratings.join(data.movies['genres'],on = 'item')
joined_data =joined_data.join(data.movies['title'],on = 'item')
joined_data.head(10)

,user,item,rating,timestamp,genres,title
0,1,1,4.0,964982703,Adventure|Animation|Children|Comedy|Fantasy,Toy Story (1995)
1,1,3,4.0,964981247,Comedy|Romance,Grumpier Old Men (1995)
2,1,6,4.0,964982224,Action|Crime|Thriller,Heat (1995)
3,1,47,5.0,964983815,Mystery|Thriller,Seven (a.k.a. Se7en) (1995)
4,1,50,5.0,964982931,Crime|Mystery|Thriller,"Usual Suspects, The (1995)"
5,1,70,3.0,964982400,Action|Comedy|Horror|Thriller,From Dusk Till Dawn (1996)
6,1,101,5.0,964980868,Adventure|Comedy|Crime|Romance,Bottle Rocket (1996)
7,1,110,4.0,964982176,Action|Drama|War,Braveheart (1995)
8,1,151,5.0,964984041,Action|Drama|Romance|War,Rob Roy (1995)
9,1,157,5.0,964984100,Comedy|War,Canadian Bacon (1995)

In [5]:
minimum_to_include = 20 #<-- You can try changing this minimum to include movies rated by fewer or more people

average_ratings = (data.ratings).groupby(['item']).mean()
rating_counts = (data.ratings).groupby(['item']).count()
average_ratings = average_ratings.loc[rating_counts['rating'] > minimum_to_include]
sorted_avg_ratings = average_ratings.sort_values(by="rating", ascending=False)
joined_data = sorted_avg_ratings.join(data.movies['genres'], on='item')
joined_data = joined_data.join(data.movies['title'], on='item')
joined_data = joined_data[joined_data.columns[3:]]

print("RECOMMENDED FOR ANYBODY:")
joined_data.head(10)

RECOMMENDED FOR ANYBODY:

,genres,title
item,,
318,Crime|Drama,"Shawshank Redemption, The (1994)"
922,Drama|Film-Noir|Romance,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)
898,Comedy|Drama|Romance,"Philadelphia Story, The (1940)"
475,Drama,In the Name of the Father (1993)
1204,Adventure|Drama|War,Lawrence of Arabia (1962)
246,Documentary,Hoop Dreams (1994)
858,Crime|Drama,"Godfather, The (1972)"
1235,Comedy|Drama|Romance,Harold and Maude (1971)
168252,Action|Sci-Fi,Logan (2017)
2959,Action|Crime|Drama|Thriller,Fight Club (1999)

In [6]:
average_ratings = (data.ratings).groupby(['item']).mean()
rating_counts = (data.ratings).groupby(['item']).count()
average_ratings = average_ratings.loc[rating_counts['rating'] > minimum_to_include]
average_ratings = average_ratings.join(data.movies['genres'], on='item')
average_ratings = average_ratings.loc[average_ratings['genres'].str.contains('Action')]

sorted_avg_ratings = average_ratings.sort_values(by="rating", ascending=False)
joined_data = sorted_avg_ratings.join(data.movies['title'], on='item')
joined_data = joined_data[joined_data.columns[3:]]
print("RECOMMENDED FOR AN ACTION MOVIE FAN:")
joined_data.head(20)

RECOMMENDED FOR AN ACTION MOVIE FAN:

,genres,title
item,,
168252,Action|Sci-Fi,Logan (2017)
2959,Action|Crime|Drama|Thriller,Fight Club (1999)
58559,Action|Crime|Drama|IMAX,"Dark Knight, The (2008)"
1197,Action|Adventure|Comedy|Fantasy|Romance,"Princess Bride, The (1987)"
260,Action|Adventure|Sci-Fi,Star Wars: Episode IV - A New Hope (1977)
3275,Action|Crime|Drama|Thriller,"Boondock Saints, The (2000)"
1208,Action|Drama|War,Apocalypse Now (1979)
1196,Action|Adventure|Sci-Fi,Star Wars: Episode V - The Empire Strikes Back...
1233,Action|Drama|War,"Boot, Das (Boat, The) (1981)"
1198,Action|Adventure,Raiders of the Lost Ark (Indiana Jones and the...
2571,Action|Sci-Fi|Thriller,"Matrix, The (1999)"
2019,Action|Adventure|Drama,Seven Samurai (Shichinin no samurai) (1954)
908,Action|Adventure|Mystery|Romance|Thriller,North by Northwest (1959)
3681,Action|Drama|Thriller|Western,For a Few Dollars More (Per qualche dollaro in...
6016,Action|Adventure|Crime|Drama|Thriller,City of God (Cidade de Deus) (2002)
2028,Action|Drama|War,Saving Private Ryan (1998)
1201,Action|Adventure|Western,"Good, the Bad and the Ugly, The (Buono, il bru..."
1210,Action|Adventure|Sci-Fi,Star Wars: Episode VI - Return of the Jedi (1983)
68157,Action|Drama|War,Inglourious Basterds (2009)
1262,Action|Adventure|Drama|War,"Great Escape, The (1963)"

In [14]:
import csv

Dennis_rating_dict = {}

with open("Dennis-movie-ratings.csv", newline='') as csvfile:
  ratings_reader = csv.DictReader(csvfile)
  for row in ratings_reader:
    if ((row['ratings'] != "") and (float(row['ratings']) > 0) and (float(row['ratings']) < 6)):
      Dennis_rating_dict.update({int(row['item']): float(row['ratings'])})
      

print("Rating dictionaries assembled!")
print("Sanity check:")
print("\tDennis's rating for 1197 (The Princess Bride) is " + str(Dennis_rating_dict[1197]))

Rating dictionaries assembled!
Sanity check:
	Dennis's rating for 1197 (The Princess Bride) is 4.5

In [15]:
from lenskit.algorithms import Recommender
from lenskit.algorithms.user_knn import UserUser

num_recs = 10  #<---- This is the number of recommendations to generate. You can change this if you want to see more recommendations

user_user = UserUser(15, min_nbrs=3) #These two numbers set the minimum (3) and maximum (15) number of neighbors to consider. These are considered "reasonable defaults," but you can experiment with others too
algo = Recommender.adapt(user_user)
algo.fit(data.ratings)

print("Set up a User-User algorithm!")

Set up a User-User algorithm!

In [19]:
Dennis_recs = algo.recommend(-1, num_recs, ratings=pd.Series(Dennis_rating_dict))  #Here, -1 tells it that it's not an existing user in the set, that we're giving new ratings, while 10 is how many recommendations it should generate

joined_data = Dennis_recs.join(data.movies['genres'], on='item')      
joined_data = joined_data.join(data.movies['title'], on='item')
joined_data = joined_data[joined_data.columns[2:]]
print("\n\nRECOMMENDED FOR Dennis:")
joined_data

RECOMMENDED FOR Dennis:

,genres,title
0,Comedy|Drama,"Last Detail, The (1973)"
1,Comedy,Love and Death (1975)
2,Drama,Before Night Falls (2000)
3,Drama,"Magdalene Sisters, The (2002)"
4,Drama|Horror|Mystery|Sci-Fi|Thriller,Black Mirror: White Christmas (2014)
5,Action|Animation|Drama|Fantasy|Sci-Fi,Neon Genesis Evangelion: The End of Evangelion...
6,Action|Adventure|Thriller,Raiders of the Lost Ark: The Adaptation (1989)
7,Comedy|Drama|Romance,Submarine (2010)
8,Adventure|Drama,Nebraska (2013)
9,Documentary,"Endless Summer, The (1966)"

In [22]:
##Futhur STEP 
##making a combined movie recommendation list for entire team

Dennis-movie-ratings.numbers* data/
Movie-recommendation-system/  remmendation system.ipynb